// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  standards: [{ type: "autogenerated", dirName: "standards" }],
  ["radically-digital"]: [
    { type: "autogenerated", dirName: "radically-digital" },
  ],
};

module.exports = sidebars;
