// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  standards: [{ type: "autogenerated", dirName: "standards" }],
  learning: [{ type: "autogenerated", dirName: "learning" }],
  techniques: [{ type: "autogenerated", dirName: "techniques" }],
};

module.exports = sidebars;
